"""QR 생성 + 사진·QR을 base64 data URI CSS로 출력. 실행: python3 assets/build_assets.py"""

from __future__ import annotations

import base64
from PIL import Image
from pathlib import Path

import segno

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
SITE_URL = "https://rukkha1024.github.io"
MAIL_URL = "mailto:cho9911@gmail.com"

TARGETS = {
    "qr_site.png": SITE_URL,
    "qr_mail.png": MAIL_URL,
}


def build_qr(path: Path, payload: str) -> None:
    qr = segno.make(payload, error="m")
    qr.save(str(path), scale=6, border=1, dark="#000000", light="#ffffff")


def data_uri(path: Path) -> str:
    mime = "image/png" if path.suffix == ".png" else "image/jpeg"
    return f"data:{mime};base64,{base64.b64encode(path.read_bytes()).decode()}"


def main() -> None:
    for name, payload in TARGETS.items():
        build_qr(HERE / name, payload)
    # images/profile.png is JPEG data despite its suffix. Downscale for a ~1.1in print box (300 dpi).
    img = Image.open(REPO / "images" / "profile.png").convert("RGB")
    img.thumbnail((330, 440))
    img.save(HERE / "profile.jpg", "JPEG", quality=82, optimize=True)

    css = [
        "/* generated by assets/build_assets.py — do not edit */",
        # Photo stays a public URL: the base64 JPEG is too long to pass safely through the MCP call.
        f".photo {{ background-image: url({SITE_URL}/images/profile.png); }}",
        f".qr-site {{ background-image: url({data_uri(HERE / 'qr_site.png')}); }}",
        f".qr-mail {{ background-image: url({data_uri(HERE / 'qr_mail.png')}); }}",
    ]
    (HERE / "print_assets.css").write_text("\n".join(css) + "\n", encoding="utf-8")
    print("wrote", HERE / "print_assets.css")


if __name__ == "__main__":
    main()
